### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Alejuda** [mutugi-c/Geospatial-World-Forum#2]
### Peer-To-Peer Code Review 👌🏼 

Hello @mutugi-c! You did a great job with your capstone project. Your web seems very professional and all links works correctly. We just wanted to recommend you to add two new propertyes to de #header background img so it doesn't repeat and it cover the hole section:
```css
#header {
background-repeat: no-repeat;
background-size: cover;
}
```
https://github.com/mutugi-c/Geospatial-World-Forum/blob/486528378f1d0c11b569a74f2ef7c82da9423551/css/styles.css#LL238C12-L238C12

And finally one more thing that could make your web more professional is adding a transparent border to de .main__info container so it just change the color on :hover. You will see that the height of the section does not change when you hover each card.

```css
.main__info {
border: 1px solid transparent;
}
```

https://github.com/mutugi-c/Geospatial-World-Forum/blob/486528378f1d0c11b569a74f2ef7c82da9423551/css/styles.css#L339
